name: Build Docker image and deploy to Heroku
on:
  push:
    branches:
      - main  # Adjust to your default branch
  schedule:
    - cron: '0 8 */2 * *'
jobs:
    collect_data:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.x

      - name: Install dependencies
        run: |
          pip install -r requirements_collect_data.txt

      - name: Run Python script
        run: python get_data.py  # Replace with the actual command to run your Python script

      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add .
          git commit -am "GH ACTION Headlines $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Login to Heroku Container registry
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          run: heroku container:login
        - name: Build and push
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            NOTION_KEY: ${{ secrets.NOTION_KEY }}
            OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
            parent_page_id: ${{ secrets.parent_page_id }}
          run: heroku container:push -a guarded-caverns-78210 web
        - name: Release
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            NOTION_KEY: ${{ secrets.NOTION_KEY }}
            OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
            parent_page_id: ${{ secrets.parent_page_id }}
          run: heroku container:release -a guarded-caverns-78210 web