name: Build Docker image and deploy to Heroku
on:
  push:
    branches:
      - main  # Adjust to your default branch
  schedule:
    - cron: '0 8 */2 * *'
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Login to Heroku Container registry
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          run: heroku container:login
        - name: Build and push
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          run: heroku container:push -a guarded-caverns-78210 web
        - name: Release
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          run: heroku container:release -a guarded-caverns-78210 web