name: Build Docker image and deploy to Heroku

on:
  push:
    branches:
      - main  # Adjust to your default branch
  schedule:
    - cron: '0 7 */3 * *'

jobs:
  collect_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.x

    - name: Install dependencies
      run: |
        pip install -r requirements_collect_data.txt

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create secret.py file
      run: |
        echo "def get_openai_key():" > secret.py
        echo "    return '${{ secrets.OPENAI_KEY }}'" >> secret.py

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker build -t mydocker .

    - name: Log in to Heroku Container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com

    - name: Push Docker image to Heroku
      run: |
        docker tag mydocker registry.heroku.com/guarded-caverns-78210/web
        docker push registry.heroku.com/guarded-caverns-78210/web

    - name: Release the Heroku app
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        curl -n -X PATCH https://api.heroku.com/apps/guarded-caverns-78210/formation \
          -d '{ "updates": [ { "type": "web", "docker_image": "registry.heroku.com/guarded-caverns-78210/web" } ] }' \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
          -H "Authorization: Bearer $HEROKU_API_KEY"