name: Build Docker image and deploy to Heroku
on:
  push:
    branches:
      - main  # Adjust to your default branch
  schedule:
    - cron: '0 8 */2 * *'  # Run at 8 AM every other day
    - cron: '0 20 1-31/2 * *'  # Run at 8 PM every other day
jobs:

    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1

        - name: Install Heroku CLI
          run: |
            curl https://cli-assets.heroku.com/install.sh | sh

        - name: Build and Push Docker image to Heroku
          run: |
            echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
            docker build -t registry.heroku.com/jobzoeker/web .
            docker push registry.heroku.com/jobzoeker/web
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

        - name: Release Docker image on Heroku
          run: |
            heroku container:release web -a jobzoeker
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            NOTION_KEY: ${{ secrets.NOTION_KEY }}
            OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
            parent_page_id: ${{ secrets.parent_page_id }}
